export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
export const TOAST_SHOW = 'TOAST_SHOW';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const CATELOG_SELECTED_TAB='CATELOG_SELECTED_TAB';
export const CATELOG_SELECTED_CAT='CATELOG_SELECTED_CAT';
export const CATELOG_SELECTED_L1CAT='CATELOG_SELECTED_L1CAT';
export const CATELOG_SELECTED_L2CAT='CATELOG_SELECTED_L2CAT';
export const CATELOG_CATEGORY_LIST='CATELOG_CATEGORY_LIST';
export const CATELOG_SUBCATEGORY_L1_LIST='CATELOG_SUBCATEGORY_L1_LIST';
export const CATELOG_SUBCATEGORY_EDIT_L1_LIST='CATELOG_SUBCATEGORY_EDIT_L1_LIST';
export const CATELOG_SUBCATEGORY_L2_LIST='CATELOG_SUBCATEGORY_L2_LIST';
export const CATELOG_PRODUCT_LIST='CATELOG_PRODUCT_LIST';
export const CATELOG_ADD_CAT='CATELOG_ADD_CAT';
export const CATELOG_ADD_L1CAT='CATELOG_ADD_L1CAT';
export const CATELOG_ADD_L2CAT='CATELOG_ADD_L2CAT';
export const CATELOG_EDIT_CAT='CATELOG_EDIT_CAT';
export const CATELOG_EDIT_L1CAT='CATELOG_EDIT_L1CAT';
export const CATELOG_EDIT_L2CAT='CATELOG_EDIT_L2CAT';
export const CATELOG_CLEAR_FROM='CATELOG_CLEAR_FROM';

export const PRODUCT_VIEW ='PRODUCT_VIEW';
export const PRODUCT_EDIT ='PRODUCT_EDIT';
export const PRODUCT_ADD ='PRODUCT_ADD';
export const UOM_LIST_VIEW ='UOM_LIST_VIEW';
export const ZONE_LIST_VIEW ='ZONE_LIST_VIEW';
export const ZONE_SELECTED ='ZONE_SELECTED';
export const WARE_HOUSE_ZONE_SELECTED ='WARE_HOUSE_ZONE_SELECTED';
export const BRAND_LIST_VIEW ='BRAND_LIST_VIEW';
export const TAG_LIST_VIEW ='TAG_LIST_VIEW';
export const UPDATE_PRODUCT_IMAGES='UPDATE_PRODUCT_IMAGES';
export const SET_PRODUCT_IMAGES='SET_PRODUCT_IMAGES';
export const DELETE_PRODUCT_IMAGES='DELETE_PRODUCT_IMAGES';
export const CLEAR_PRODUCT_DATA='CLEAR_PRODUCT_DATA';
export const EDIT_PRODUCT_VENDOR='EDIT_PRODUCT_VENDOR';
export const CLEAR_PRODUCT_VENDOR='CLEAR_PRODUCT_VENDOR';
export const CATEGORY_LIVE_UNLIVE='CATEGORY_LIVE_UNLIVE';
export const CATEGORY_LIVE_ITEM='CATEGORY_LIVE_ITEM';
export const CATEGORY_LIVE_POPUP_CLEAR='CATEGORY_LIVE_POPUP_CLEAR';
export const L1_SUBCATEGORY_LIVE_UNLIVE='L1_SUBCATEGORY_LIVE_UNLIVE';
export const L1_SUB_CATEGORY_LIVE_ITEM='L1_SUB_CATEGORY_LIVE_ITEM';
export const L1_SUB_CATEGORY_LIVE_POPUP_CLEAR='L1_SUB_CATEGORY_LIVE_POPUP_CLEAR';

export const UPDATE_CAT_IMAGES='UPDATE_CAT_IMAGES';
export const SET_CAT_IMAGES='SET_CAT_IMAGES';
export const DELETE_CAT_IMAGES='DELETE_CAT_IMAGES';


export const PRODUCT_CATEGORY_LIST='PRODUCT_CATEGORY_LIST';
export const PRODUCT_SUBCATEGORY_L1_LIST='PRODUCT_SUBCATEGORY_L1_LIST';
export const PRODUCT_SUBCATEGORY_L2_LIST='PRODUCT_SUBCATEGORY_L2_LIST';
export const CATELOG_PRODUCT_ADD_SELECT='CATELOG_PRODUCT_ADD_SELECT';
export const CATELOG_SEARCH='CATELOG_SEARCH';
export const CATELOG_SEARCH_SELECT='CATELOG_SEARCH_SELECT';

export const L2_SUBCATEGORY_LIVE_UNLIVE='L2_SUBCATEGORY_LIVE_UNLIVE';
export const L2_SUB_CATEGORY_LIVE_ITEM='L2_SUB_CATEGORY_LIVE_ITEM';
export const L2_SUB_CATEGORY_LIVE_POPUP_CLEAR='L2_SUB_CATEGORY_LIVE_POPUP_CLEAR';

export const PRODUCT_LIVE_UNLIVE='PRODUCT_LIVE_UNLIVE';
export const PRODUCT_LIVE_UNLIVE_LIVE_ITEM='PRODUCT_LIVE_UNLIVE_LIVE_ITEM';
export const PRODUCT_LIVE_UNLIVE_LIVE_POPUP_CLEAR='PRODUCT_LIVE_UNLIVE_LIVE_POPUP_CLEAR';

export const WARE_HOUSE_SELECTED_TAB='WARE_HOUSE_SELECTED_TAB';
export const DAT_ORDER_LIST='DAT_ORDER_LIST';
export const MOVE_TO_PROCUREMENT='MOVE_TO_PROCUREMENT';
export const ON_CLEAR_PROCUREMENT='ON_CLEAR_PROCUREMENT';
