export const SIGN_UP_FORM = "signup";
export const SEARCH_INPUT="search_input"
export const SEARCH_INPUT_FILTER="search_input_filter"
export const SEARCH_NEW="search_new"
export const SEARCH_ITEM="search_item"
export const PRODUCT_ADD_EDIT="product_add_edit"
export const VENDOR_EDIT="vendor_edit"
export const VENDOR_ASSIGN="vendor_assign"
export const CAT_SUB_ADD_EDIT="cat_sub_add_edit"
export const RECEIVING_FORM="receiving_form"
export const STOCK_ADD_FORM="stock_add_form"
export const LoginType={1:"/",2:"/",3:"/makeit-vorders",4:"/",5:"/",6:"/"};
export const MasterOrderStatusV={0:"Post",1:"Accept",2:"Preparing",3:"Prepared",5:"Pickedup",6:"Delivered",7:"Cancel"};
export const MasterOrderStatus={0:"Open",1:"SCM",2:"SCM",3:"SCM",5:"SCM",6:"Ready to dispatch",7:"Cancel"};
export const notification_color = { background: "#ffffff", text: "#000000" };