export const SIGN_UP_FORM = "signup";
export const SEARCH_INPUT="search_input"
export const SEARCH_INPUT_FILTER="search_input_filter"
export const SEARCH_NEW="search_new"
export const SEARCH_ITEM="search_item"
export const SEARCH_TRIP="search_trip"
export const PRODUCT_ADD_EDIT="product_add_edit"
export const VENDOR_EDIT="vendor_edit"
export const VENDOR_ASSIGN="vendor_assign"
export const CAT_SUB_ADD_EDIT="cat_sub_add_edit"
export const ADDRESS_FORM="address_form"
export const COMMUNITY_FORM="community_form"
export const ORDER_VIEW_FORM="order_view_from"
export const RECEIVING_FORM="receiving_form"
export const STOCK_ADD_FORM="stock_add_form"
export const COMMENT_ENTER_FORM="comment_form"
export const PO_COMMEND_FORM="po_commend_form"
export const MOVEIT_REGISTRATION_FORM="moveit_registaration"
export const MOBILE_NUMBER_VERIFY="moveit_number_verify"
export const LoginType={1:"/",2:"/",3:"/makeit-vorders",4:"/",5:"/",6:"/"};
export const MasterOrderStatusV={0:"Post",1:"Accept",2:"Preparing",3:"Prepared",5:"Pickedup",6:"Delivered",7:"Cancel"};
export const MasterPOStatus={0:"Request",1:"Received",2:"Un Received",3:"Close",4:"Deleted"};
export const MasterOrderStatus={0:"Open",1:"SCM",2:"SCM",3:"SCM",5:"SCM",6:"Ready to dispatch",7:"Moveit Assign",8:"Moveit Pickup",9:"Moveit Delivered",10:"Completed",11:"Cancel",12:"Return"};
export const notification_color = { background: "#ffffff", text: "#000000" };
export const PUSH_NOTIFICATION_FROM="push_notification_from"