import { MdDashboard } from "react-icons/md";
export const SidebarSuperAdmin = [
  {
    to: "/community/master",
    name: "DL Exclusive",
    exact: true,
    Icon: MdDashboard,
    submenu: false,
    submenuItem: null,
    enable_action: "catalog_sidenav",
  },
  {
    to: "/dashboard",
    name: "Catalog",
    exact: true,
    Icon: MdDashboard,
    submenu: false,
    submenuItem: null,
    enable_action: "catalog_sidenav",
  },
  {
    to: "/stock/keeping",
    name: "Stock keeping",
    exact: true,
    Icon: MdDashboard,
    submenu: false,
    submenuItem: null,
    enable_action: "stock_keeping_sidenav",
  },
  {
    to: "/warehouse/dayoders",
    name: "Warehouse",
    exact: true,
    Icon: MdDashboard,
    submenu: false,
    submenuItem: null,
    enable_action: "warehouse_sidenav",
  },
  {
    to: "/crm",
    name: "Orders",
    exact: true,
    Icon: MdDashboard,
    submenu: false,
    submenuItem: null,
    enable_action: "crm_sidenav",
  },
  {
    to: "/user",
    name: "User",
    exact: true,
    Icon: MdDashboard,
    submenu: false,
    submenuItem: null,
    enable_action: "user_sidenav",
  },
  {
    to: "/logistics",
    name: "Logistics",
    exact: true,
    Icon: MdDashboard,
    submenu: false,
    submenuItem: null,
    enable_action: "logistics_sidenav",
  },
  {
    to: "/dunzo_orders",
    name: "Dunzo Orders",
    exact: true,
    Icon: MdDashboard,
    submenu: false,
    submenuItem: null,
    enable_action: "dunzo_sidenav",
  },
  {
    to: "/trip_orders",
    name: "Trip Orders",
    exact: true,
    Icon: MdDashboard,
    submenu: false,
    submenuItem: null,
    enable_action: "trip_sidenav",
  },
  {
    to: "/moveit-list",
    name: "Drivers",
    exact: true,
    Icon: MdDashboard,
    submenu: false,
    submenuItem: null,
    enable_action: "driver_sidenav",
  },
  {
    to: "/refund-approval",
    name: "Refund approval",
    exact: true,
    Icon: MdDashboard,
    submenu: false,
    submenuItem: null,
    enable_action: "refund_sidenav",
  },
];
export const navBarSuperAdminItems = [];
